/**
 * Created by LQZ on 2017/6/21.
 */
export const ADD_SUBJECT_NUM = 'ADD_SUBJECT_NUM'
export const CHANGE_SUBJECT_NOWKEY = 'CHANGE_SUBJECT_NOWKEY'
export const CHANGE_SUBJECT_RIGHTKEY = 'CHANGE_SUBJECT_RIGHTKEY'
export const CHANGE_SUBJECT_LASTTYPE = 'CHANGE_SUBJECT_LASTTYPE'
export const CHANGE_SUBJECT_NOWTYPE = 'CHANGE_SUBJECT_NOWTYPE'
export const RECOVERY_SUBJECT_KEY = 'RECOVERY_SUBJECT_KEY'
export const CHANGE_RESULT_SELCET = 'CHANGE_RESULT_SELCET'
export const CHANGE_LOGIN_TYPE = 'CHANGE_LOGIN_TYPE'
export const COUNT_ALL_TIME = 'COUNT_ALL_TIME'
export const COUNT_PASS_NUM = 'COUNT_PASS_NUM'
export const CLEAR_STATE = 'CLEAR_STATE'
